import "./globals.css";
import { Inter } from "next/font/google";
import TodoProvider from "../../provider/TodoProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TodoProvider>
        <body className={inter.className}>{children}</body>
      </TodoProvider>
    </html>
  );
}
